"""Unit tests for the exchange module.

Tests for the file exchange logic that handles communication between
popctl and AI advisors via scan.json and decisions.toml files.
"""

from __future__ import annotations

from pathlib import Path

import pytest
from popctl.advisor.exchange import (
    ConfigOrphanEntry,
    DecisionsResult,
    DomainDecisions,
    FilesystemOrphanEntry,
    PackageDecision,
    PackageScanEntry,
    PathDecision,
    ScanExport,
    SourceDecisions,
    import_decisions,
)

# =============================================================================
# Test Fixtures
# =============================================================================


@pytest.fixture
def valid_decisions_toml() -> str:
    """Valid decisions.toml content for testing."""
    return """
# Generated by AI Advisor
# Date: 2026-01-25T12:00:00Z

[packages.apt]
keep = [
    { name = "firefox", reason = "Web browser", confidence = 0.95, category = "desktop" },
    { name = "libgtk-3-0", reason = "GUI library", confidence = 0.98, category = "system" },
]
remove = [
    { name = "apport", reason = "Telemetry", confidence = 0.92, category = "telemetry" },
]
ask = [
    { name = "gcc", reason = "Dev tools", confidence = 0.65, category = "development" },
]

[packages.flatpak]
keep = [
    { name = "com.spotify.Client", reason = "Music app", confidence = 0.90, category = "media" },
]
remove = []
ask = []

[packages.snap]
keep = [
    { name = "vlc", reason = "Media player", confidence = 0.92, category = "media" },
]
remove = [
    { name = "telegram-desktop", reason = "Use flatpak", confidence = 0.88, category = "desktop" },
]
ask = []
"""


@pytest.fixture
def invalid_category_toml() -> str:
    """decisions.toml with invalid category."""
    return """
[packages.apt]
keep = [
    { name = "test", reason = "test", confidence = 0.95, category = "invalid_category" },
]
remove = []
ask = []

[packages.flatpak]
keep = []
remove = []
ask = []
"""


@pytest.fixture
def invalid_toml_syntax() -> str:
    """Invalid TOML syntax for testing."""
    return """
[packages.apt
keep = [
    { name = "test", reason = "test"
]
"""


# =============================================================================
# Test PackageScanEntry Model
# =============================================================================


class TestPackageScanEntry:
    """Tests for PackageScanEntry Pydantic model."""

    def test_create_entry_with_all_fields(self) -> None:
        """PackageScanEntry accepts all fields."""
        entry = PackageScanEntry(
            name="firefox",
            source="apt",
            version="128.0",
            status="manual",
            description="Web browser",
            size_bytes=204800,
        )

        assert entry.name == "firefox"
        assert entry.source == "apt"
        assert entry.version == "128.0"
        assert entry.status == "manual"
        assert entry.description == "Web browser"
        assert entry.size_bytes == 204800

    def test_create_entry_with_minimal_fields(self) -> None:
        """PackageScanEntry works with minimal required fields."""
        entry = PackageScanEntry(
            name="test",
            source="apt",
            version="1.0",
            status="manual",
        )

        assert entry.name == "test"
        assert entry.description is None
        assert entry.size_bytes is None

    def test_entry_is_frozen(self) -> None:
        """PackageScanEntry is immutable."""
        entry = PackageScanEntry(
            name="test",
            source="apt",
            version="1.0",
            status="manual",
        )

        from pydantic import ValidationError

        with pytest.raises(ValidationError):  # Pydantic frozen models raise ValidationError
            entry.name = "changed"  # type: ignore[misc]


# =============================================================================
# Test ScanExport Model
# =============================================================================


class TestScanExport:
    """Tests for ScanExport Pydantic model."""

    def test_create_scan_export(self) -> None:
        """ScanExport accepts complete data."""
        entries = [
            PackageScanEntry(
                name="firefox",
                source="apt",
                version="128.0",
                status="manual",
            )
        ]

        export = ScanExport(
            scan_date="2026-01-25T12:00:00Z",
            system={"hostname": "test-host", "os": "Pop!_OS 24.04 LTS"},
            summary={"total_packages": 1, "manual_apt": 1},
            packages={"unknown": entries, "new_since_manifest": []},
        )

        assert export.scan_date == "2026-01-25T12:00:00Z"
        assert export.system["hostname"] == "test-host"
        assert export.summary["total_packages"] == 1
        assert len(export.packages["unknown"]) == 1


# =============================================================================
# Test PackageDecision Model
# =============================================================================


class TestPackageDecision:
    """Tests for PackageDecision Pydantic model."""

    def test_create_valid_decision(self) -> None:
        """PackageDecision accepts valid data."""
        decision = PackageDecision(
            name="firefox",
            reason="Web browser needed",
            confidence=0.95,
            category="desktop",
        )

        assert decision.name == "firefox"
        assert decision.reason == "Web browser needed"
        assert decision.confidence == 0.95
        assert decision.category == "desktop"

    def test_decision_validates_confidence_range(self) -> None:
        """PackageDecision validates confidence is between 0.0 and 1.0."""
        # Valid boundary values
        PackageDecision(name="test", reason="test", confidence=0.0, category="system")
        PackageDecision(name="test", reason="test", confidence=1.0, category="system")

        # Invalid values
        with pytest.raises(ValueError):
            PackageDecision(name="test", reason="test", confidence=-0.1, category="system")

        with pytest.raises(ValueError):
            PackageDecision(name="test", reason="test", confidence=1.1, category="system")

    def test_decision_validates_category(self) -> None:
        """PackageDecision validates category against CATEGORIES."""
        from popctl.advisor.prompts import CATEGORIES

        # Valid categories
        for cat in CATEGORIES:
            decision = PackageDecision(name="test", reason="test", confidence=0.5, category=cat)
            assert decision.category == cat

        # Invalid category
        with pytest.raises(ValueError, match="Invalid category"):
            PackageDecision(name="test", reason="test", confidence=0.5, category="invalid_cat")


# =============================================================================
# Test SourceDecisions Model
# =============================================================================


class TestSourceDecisions:
    """Tests for SourceDecisions Pydantic model."""

    def test_source_decisions_defaults_to_empty_lists(self) -> None:
        """SourceDecisions defaults to empty lists."""
        decisions = SourceDecisions()

        assert decisions.keep == []
        assert decisions.remove == []
        assert decisions.ask == []

    def test_source_decisions_accepts_lists(self) -> None:
        """SourceDecisions accepts decision lists."""
        keep = [
            PackageDecision(name="pkg1", reason="r1", confidence=0.95, category="system"),
        ]
        remove = [
            PackageDecision(name="pkg2", reason="r2", confidence=0.90, category="telemetry"),
        ]

        decisions = SourceDecisions(keep=keep, remove=remove)

        assert len(decisions.keep) == 1
        assert len(decisions.remove) == 1
        assert len(decisions.ask) == 0


# =============================================================================
# Test DecisionsResult Model
# =============================================================================


class TestDecisionsResult:
    """Tests for DecisionsResult Pydantic model."""

    def test_decisions_result_structure(self) -> None:
        """DecisionsResult has correct structure."""
        apt_decisions = SourceDecisions(
            keep=[PackageDecision(name="apt-pkg", reason="r", confidence=0.9, category="system")]
        )
        flatpak_decisions = SourceDecisions()
        snap_decisions = SourceDecisions()

        result = DecisionsResult(
            packages={
                "apt": apt_decisions,
                "flatpak": flatpak_decisions,
                "snap": snap_decisions,
            }
        )

        assert "apt" in result.packages
        assert "flatpak" in result.packages
        assert "snap" in result.packages
        assert len(result.packages["apt"].keep) == 1


# =============================================================================
# Test import_decisions
# =============================================================================


class TestImportDecisions:
    """Tests for import_decisions function."""

    def test_import_valid_decisions(self, tmp_path: Path, valid_decisions_toml: str) -> None:
        """import_decisions parses valid decisions.toml."""
        decisions_path = tmp_path / "decisions.toml"
        decisions_path.write_text(valid_decisions_toml)

        result = import_decisions(tmp_path)

        assert isinstance(result, DecisionsResult)
        assert "apt" in result.packages
        assert "flatpak" in result.packages
        assert "snap" in result.packages

    def test_import_parses_keep_list(self, tmp_path: Path, valid_decisions_toml: str) -> None:
        """import_decisions correctly parses keep list."""
        decisions_path = tmp_path / "decisions.toml"
        decisions_path.write_text(valid_decisions_toml)

        result = import_decisions(tmp_path)

        apt_keep = result.packages["apt"].keep
        assert len(apt_keep) == 2

        firefox = next(d for d in apt_keep if d.name == "firefox")
        assert firefox.reason == "Web browser"
        assert firefox.confidence == 0.95
        assert firefox.category == "desktop"

    def test_import_parses_remove_list(self, tmp_path: Path, valid_decisions_toml: str) -> None:
        """import_decisions correctly parses remove list."""
        decisions_path = tmp_path / "decisions.toml"
        decisions_path.write_text(valid_decisions_toml)

        result = import_decisions(tmp_path)

        apt_remove = result.packages["apt"].remove
        assert len(apt_remove) == 1
        assert apt_remove[0].name == "apport"
        assert apt_remove[0].category == "telemetry"

    def test_import_parses_ask_list(self, tmp_path: Path, valid_decisions_toml: str) -> None:
        """import_decisions correctly parses ask list."""
        decisions_path = tmp_path / "decisions.toml"
        decisions_path.write_text(valid_decisions_toml)

        result = import_decisions(tmp_path)

        apt_ask = result.packages["apt"].ask
        assert len(apt_ask) == 1
        assert apt_ask[0].name == "gcc"
        assert apt_ask[0].confidence == 0.65

    def test_import_parses_flatpak_decisions(
        self, tmp_path: Path, valid_decisions_toml: str
    ) -> None:
        """import_decisions correctly parses flatpak section."""
        decisions_path = tmp_path / "decisions.toml"
        decisions_path.write_text(valid_decisions_toml)

        result = import_decisions(tmp_path)

        flatpak_keep = result.packages["flatpak"].keep
        assert len(flatpak_keep) == 1
        assert flatpak_keep[0].name == "com.spotify.Client"
        assert flatpak_keep[0].category == "media"

    def test_import_parses_snap_decisions(self, tmp_path: Path, valid_decisions_toml: str) -> None:
        """import_decisions correctly parses snap section."""
        decisions_path = tmp_path / "decisions.toml"
        decisions_path.write_text(valid_decisions_toml)

        result = import_decisions(tmp_path)

        snap_keep = result.packages["snap"].keep
        assert len(snap_keep) == 1
        assert snap_keep[0].name == "vlc"
        assert snap_keep[0].category == "media"
        assert snap_keep[0].confidence == 0.92

        snap_remove = result.packages["snap"].remove
        assert len(snap_remove) == 1
        assert snap_remove[0].name == "telegram-desktop"

    def test_import_handles_missing_snap_section(self, tmp_path: Path) -> None:
        """import_decisions handles missing snap section gracefully."""
        decisions_toml = """
[packages.apt]
keep = []
remove = []
ask = []

[packages.flatpak]
keep = []
remove = []
ask = []
# snap section missing
"""
        decisions_path = tmp_path / "decisions.toml"
        decisions_path.write_text(decisions_toml)

        result = import_decisions(tmp_path)

        # Should have empty snap decisions
        assert "snap" in result.packages
        assert result.packages["snap"].keep == []
        assert result.packages["snap"].remove == []
        assert result.packages["snap"].ask == []

    def test_import_raises_file_not_found(self, tmp_path: Path) -> None:
        """import_decisions raises FileNotFoundError if file missing."""
        with pytest.raises(FileNotFoundError, match="decisions.toml not found"):
            import_decisions(tmp_path)

    def test_import_raises_on_invalid_toml(self, tmp_path: Path, invalid_toml_syntax: str) -> None:
        """import_decisions raises ValueError on invalid TOML syntax."""
        decisions_path = tmp_path / "decisions.toml"
        decisions_path.write_text(invalid_toml_syntax)

        with pytest.raises(ValueError, match="Invalid TOML"):
            import_decisions(tmp_path)

    def test_import_raises_on_invalid_category(
        self, tmp_path: Path, invalid_category_toml: str
    ) -> None:
        """import_decisions raises ValueError on invalid category."""
        decisions_path = tmp_path / "decisions.toml"
        decisions_path.write_text(invalid_category_toml)

        with pytest.raises(ValueError, match="Invalid category"):
            import_decisions(tmp_path)

    def test_import_handles_empty_lists(self, tmp_path: Path) -> None:
        """import_decisions handles empty decision lists."""
        decisions_toml = """
[packages.apt]
keep = []
remove = []
ask = []

[packages.flatpak]
keep = []
remove = []
ask = []

[packages.snap]
keep = []
remove = []
ask = []
"""
        decisions_path = tmp_path / "decisions.toml"
        decisions_path.write_text(decisions_toml)

        result = import_decisions(tmp_path)

        assert result.packages["apt"].keep == []
        assert result.packages["apt"].remove == []
        assert result.packages["apt"].ask == []
        assert result.packages["snap"].keep == []
        assert result.packages["snap"].remove == []
        assert result.packages["snap"].ask == []

    def test_import_handles_missing_source(self, tmp_path: Path) -> None:
        """import_decisions handles missing source sections."""
        decisions_toml = """
[packages.apt]
keep = []
remove = []
ask = []
# flatpak and snap sections missing
"""
        decisions_path = tmp_path / "decisions.toml"
        decisions_path.write_text(decisions_toml)

        result = import_decisions(tmp_path)

        # Should have empty flatpak and snap decisions
        assert result.packages["flatpak"].keep == []
        assert result.packages["flatpak"].remove == []
        assert result.packages["snap"].keep == []
        assert result.packages["snap"].remove == []


# =============================================================================
# Test Module Exports
# =============================================================================


class TestModuleExports:
    """Tests for module-level exports."""

    def test_exchange_module_exports(self) -> None:
        """exchange module exports expected symbols."""
        from popctl.advisor import exchange

        # Models
        assert hasattr(exchange, "PackageScanEntry")
        assert hasattr(exchange, "ScanExport")
        assert hasattr(exchange, "PackageDecision")
        assert hasattr(exchange, "SourceDecisions")
        assert hasattr(exchange, "DecisionsResult")
        assert hasattr(exchange, "PathDecision")
        assert hasattr(exchange, "DomainDecisions")
        assert hasattr(exchange, "FilesystemOrphanEntry")
        assert hasattr(exchange, "ConfigOrphanEntry")

        # Functions
        assert hasattr(exchange, "import_decisions")

    def test_advisor_init_exports_exchange(self) -> None:
        """advisor __init__ exports exchange symbols."""
        from popctl.advisor import (
            ConfigOrphanEntry,
            DecisionsResult,
            DomainDecisions,
            FilesystemOrphanEntry,
            PackageDecision,
            PackageScanEntry,
            PathDecision,
            ScanExport,
            SourceDecisions,
            import_decisions,
        )

        # Verify imports work and are callable/classes
        assert callable(import_decisions)
        assert PackageScanEntry is not None
        assert ScanExport is not None
        assert PackageDecision is not None
        assert SourceDecisions is not None
        assert DecisionsResult is not None
        assert PathDecision is not None
        assert DomainDecisions is not None
        assert FilesystemOrphanEntry is not None
        assert ConfigOrphanEntry is not None


# =============================================================================
# Test FilesystemOrphanEntry Model
# =============================================================================


class TestFilesystemOrphanEntry:
    """Tests for FilesystemOrphanEntry Pydantic model."""

    def test_filesystem_orphan_entry_creation(self) -> None:
        """FilesystemOrphanEntry accepts all fields."""
        from popctl.advisor.exchange import FilesystemOrphanEntry

        entry = FilesystemOrphanEntry(
            path="~/.config/vlc",
            path_type="directory",
            size_bytes=4096,
            mtime="2024-01-15T10:00:00Z",
            parent_target="~/.config",
            orphan_reason="no_package_match",
            confidence=0.70,
        )

        assert entry.path == "~/.config/vlc"
        assert entry.path_type == "directory"
        assert entry.size_bytes == 4096
        assert entry.mtime == "2024-01-15T10:00:00Z"
        assert entry.parent_target == "~/.config"
        assert entry.orphan_reason == "no_package_match"
        assert entry.confidence == 0.70

    def test_filesystem_orphan_entry_optional_fields(self) -> None:
        """FilesystemOrphanEntry defaults optional fields to None."""
        from popctl.advisor.exchange import FilesystemOrphanEntry

        entry = FilesystemOrphanEntry(
            path="~/.config/vlc",
            path_type="directory",
            parent_target="~/.config",
            orphan_reason="no_package_match",
            confidence=0.70,
        )

        assert entry.size_bytes is None
        assert entry.mtime is None

    def test_filesystem_orphan_entry_frozen(self) -> None:
        """FilesystemOrphanEntry is immutable."""
        from popctl.advisor.exchange import FilesystemOrphanEntry
        from pydantic import ValidationError

        entry = FilesystemOrphanEntry(
            path="~/.config/vlc",
            path_type="directory",
            parent_target="~/.config",
            orphan_reason="no_package_match",
            confidence=0.70,
        )

        with pytest.raises(ValidationError):
            entry.path = "changed"  # type: ignore[misc]


# =============================================================================
# Test ScanExport with filesystem_orphans
# =============================================================================


class TestScanExportFilesystemOrphans:
    """Tests for ScanExport filesystem_orphans field."""

    def test_scan_export_filesystem_orphans_defaults(self) -> None:
        """ScanExport defaults to empty filesystem_orphans list."""
        export = ScanExport(
            scan_date="2026-01-25T12:00:00Z",
            system={"hostname": "test-host", "os": "Pop!_OS 24.04 LTS"},
            summary={"total_packages": 0},
            packages={"unknown": []},
        )

        assert export.filesystem_orphans == []

    def test_scan_export_filesystem_orphans_with_entries(self) -> None:
        """ScanExport accepts filesystem orphan entries."""
        orphan = FilesystemOrphanEntry(
            path="~/.config/vlc",
            path_type="directory",
            parent_target="~/.config",
            orphan_reason="no_package_match",
            confidence=0.70,
        )

        export = ScanExport(
            scan_date="2026-01-25T12:00:00Z",
            system={"hostname": "test-host", "os": "Pop!_OS 24.04 LTS"},
            summary={"total_packages": 0},
            packages={"unknown": []},
            filesystem_orphans=[orphan],
        )

        assert len(export.filesystem_orphans) == 1
        assert export.filesystem_orphans[0].path == "~/.config/vlc"


# =============================================================================
# Test ScanExport with Filesystem Orphans (integration)
# =============================================================================


class TestScanExportWithFilesystem:
    """Tests for ScanExport with filesystem_orphans field."""

    def test_scan_export_with_filesystem_orphans(self) -> None:
        """ScanExport includes filesystem_orphans when provided."""
        orphan = FilesystemOrphanEntry(
            path="~/.config/vlc",
            path_type="directory",
            parent_target="~/.config",
            orphan_reason="no_package_match",
            confidence=0.70,
        )

        export = ScanExport(
            scan_date="2026-01-25T12:00:00Z",
            system={"hostname": "test-host", "os": "Pop!_OS 24.04 LTS"},
            summary={"total_packages": 0},
            packages={"unknown": []},
            filesystem_orphans=[orphan],
        )

        assert len(export.filesystem_orphans) == 1
        assert export.filesystem_orphans[0].path == "~/.config/vlc"

    def test_scan_export_without_filesystem_orphans(self) -> None:
        """ScanExport defaults filesystem_orphans to empty list."""
        export = ScanExport(
            scan_date="2026-01-25T12:00:00Z",
            system={"hostname": "test-host", "os": "Pop!_OS 24.04 LTS"},
            summary={"total_packages": 0},
            packages={"unknown": []},
        )

        assert export.filesystem_orphans == []


# =============================================================================
# Test PathDecision Model
# =============================================================================


class TestPathDecision:
    """Tests for PathDecision Pydantic model."""

    def test_path_decision_creation(self) -> None:
        """PathDecision accepts valid data."""
        decision = PathDecision(
            path="~/.config/vlc",
            reason="VLC uninstalled",
            confidence=0.90,
            category="obsolete",
        )

        assert decision.path == "~/.config/vlc"
        assert decision.reason == "VLC uninstalled"
        assert decision.confidence == 0.90
        assert decision.category == "obsolete"

    def test_path_decision_validation(self) -> None:
        """PathDecision validates confidence bounds."""
        # Valid boundary values
        PathDecision(path="test", reason="test", confidence=0.0, category="other")
        PathDecision(path="test", reason="test", confidence=1.0, category="other")

        # Invalid: below 0
        with pytest.raises(ValueError):
            PathDecision(path="test", reason="test", confidence=-0.1, category="other")

        # Invalid: above 1
        with pytest.raises(ValueError):
            PathDecision(path="test", reason="test", confidence=1.1, category="other")

    def test_path_decision_frozen(self) -> None:
        """PathDecision is immutable."""
        from pydantic import ValidationError

        decision = PathDecision(path="test", reason="test", confidence=0.5, category="other")

        with pytest.raises(ValidationError):
            decision.path = "changed"  # type: ignore[misc]

    def test_path_decision_optional_category(self) -> None:
        """PathDecision allows None category."""
        decision = PathDecision(
            path="~/.config/vlc",
            reason="VLC not installed",
            confidence=0.85,
        )

        assert decision.category is None


# =============================================================================
# Test DomainDecisions Model
# =============================================================================


class TestDomainDecisions:
    """Tests for DomainDecisions Pydantic model."""

    def test_domain_decisions_defaults(self) -> None:
        """DomainDecisions defaults to empty lists."""
        decisions = DomainDecisions()

        assert decisions.keep == []
        assert decisions.remove == []
        assert decisions.ask == []

    def test_domain_decisions_with_entries(self) -> None:
        """DomainDecisions accepts path decision lists."""
        keep = [
            PathDecision(
                path="~/.config/nvim",
                reason="User config",
                confidence=0.95,
                category="config",
            )
        ]
        remove = [
            PathDecision(
                path="~/.config/vlc",
                reason="VLC removed",
                confidence=0.90,
                category="obsolete",
            )
        ]

        decisions = DomainDecisions(keep=keep, remove=remove)

        assert len(decisions.keep) == 1
        assert len(decisions.remove) == 1
        assert len(decisions.ask) == 0

    def test_domain_decisions_with_config_entries(self) -> None:
        """DomainDecisions accepts config path decision lists."""
        keep = [
            PathDecision(
                path="~/.config/nvim",
                reason="User-created Neovim configuration",
                confidence=0.95,
                category="editor",
            )
        ]
        remove = [
            PathDecision(
                path="~/.config/vlc",
                reason="VLC not installed",
                confidence=0.85,
                category="media",
            )
        ]

        decisions = DomainDecisions(keep=keep, remove=remove)

        assert len(decisions.keep) == 1
        assert len(decisions.remove) == 1
        assert len(decisions.ask) == 0


# =============================================================================
# Test DecisionsResult with Filesystem
# =============================================================================


class TestDecisionsResultWithFilesystem:
    """Tests for DecisionsResult with filesystem field."""

    def test_decisions_result_with_filesystem(self) -> None:
        """DecisionsResult includes filesystem decisions when provided."""
        fs_decisions = DomainDecisions(
            keep=[
                PathDecision(
                    path="~/.config/nvim",
                    reason="User config",
                    confidence=0.95,
                    category="config",
                )
            ],
            remove=[
                PathDecision(
                    path="~/.config/vlc",
                    reason="VLC removed",
                    confidence=0.90,
                    category="obsolete",
                )
            ],
        )

        result = DecisionsResult(
            packages={
                "apt": SourceDecisions(),
                "flatpak": SourceDecisions(),
                "snap": SourceDecisions(),
            },
            filesystem=fs_decisions,
        )

        assert result.filesystem is not None
        assert len(result.filesystem.keep) == 1
        assert len(result.filesystem.remove) == 1
        assert result.filesystem.keep[0].path == "~/.config/nvim"

    def test_decisions_result_without_filesystem(self) -> None:
        """DecisionsResult works without filesystem (backward compat)."""
        result = DecisionsResult(
            packages={
                "apt": SourceDecisions(),
                "flatpak": SourceDecisions(),
                "snap": SourceDecisions(),
            }
        )

        assert result.filesystem is None


# =============================================================================
# Test import_decisions with Filesystem
# =============================================================================


class TestImportDecisionsWithFilesystem:
    """Tests for import_decisions with filesystem section."""

    def test_import_decisions_with_filesystem(self, tmp_path: Path) -> None:
        """import_decisions parses decisions.toml with [filesystem] section."""
        decisions_toml = """
[packages.apt]
keep = []
remove = []
ask = []

[packages.flatpak]
keep = []
remove = []
ask = []

[packages.snap]
keep = []
remove = []
ask = []

[filesystem]
keep = [
    { path = "~/.config/nvim", reason = "User config", confidence = 0.95, category = "config" },
]
remove = [
    { path = "~/.config/vlc", reason = "VLC removed", confidence = 0.90, category = "obsolete" },
]
ask = [
    { path = "~/.local/share/foo", reason = "Unknown", confidence = 0.50, category = "other" },
]
"""
        decisions_path = tmp_path / "decisions.toml"
        decisions_path.write_text(decisions_toml)

        result = import_decisions(tmp_path)

        assert result.filesystem is not None
        assert len(result.filesystem.keep) == 1
        assert len(result.filesystem.remove) == 1
        assert len(result.filesystem.ask) == 1

        assert result.filesystem.keep[0].path == "~/.config/nvim"
        assert result.filesystem.keep[0].confidence == 0.95
        assert result.filesystem.keep[0].category == "config"

        assert result.filesystem.remove[0].path == "~/.config/vlc"
        assert result.filesystem.remove[0].reason == "VLC removed"

        assert result.filesystem.ask[0].path == "~/.local/share/foo"
        assert result.filesystem.ask[0].confidence == 0.50

    def test_import_decisions_without_filesystem(self, tmp_path: Path) -> None:
        """import_decisions backward compat: no [filesystem] yields None."""
        decisions_toml = """
[packages.apt]
keep = []
remove = []
ask = []

[packages.flatpak]
keep = []
remove = []
ask = []

[packages.snap]
keep = []
remove = []
ask = []
"""
        decisions_path = tmp_path / "decisions.toml"
        decisions_path.write_text(decisions_toml)

        result = import_decisions(tmp_path)

        assert result.filesystem is None

    def test_import_decisions_filesystem_empty_lists(self, tmp_path: Path) -> None:
        """import_decisions handles empty filesystem lists."""
        decisions_toml = """
[packages.apt]
keep = []
remove = []
ask = []

[packages.flatpak]
keep = []
remove = []
ask = []

[packages.snap]
keep = []
remove = []
ask = []

[filesystem]
keep = []
remove = []
ask = []
"""
        decisions_path = tmp_path / "decisions.toml"
        decisions_path.write_text(decisions_toml)

        result = import_decisions(tmp_path)

        assert result.filesystem is not None
        assert result.filesystem.keep == []
        assert result.filesystem.remove == []
        assert result.filesystem.ask == []


# =============================================================================
# Test ConfigOrphanEntry Model
# =============================================================================


class TestConfigOrphanEntry:
    """Tests for ConfigOrphanEntry Pydantic model."""

    def test_config_orphan_entry_creation(self) -> None:
        """ConfigOrphanEntry accepts all fields."""
        from popctl.advisor.exchange import ConfigOrphanEntry

        entry = ConfigOrphanEntry(
            path="~/.config/vlc",
            path_type="directory",
            size_bytes=4096,
            mtime="2024-01-15T10:00:00Z",
            orphan_reason="no_package_match",
            confidence=0.70,
        )

        assert entry.path == "~/.config/vlc"
        assert entry.path_type == "directory"
        assert entry.size_bytes == 4096
        assert entry.mtime == "2024-01-15T10:00:00Z"
        assert entry.orphan_reason == "no_package_match"
        assert entry.confidence == 0.70

    def test_config_orphan_entry_optional_fields(self) -> None:
        """ConfigOrphanEntry defaults optional fields to None."""
        from popctl.advisor.exchange import ConfigOrphanEntry

        entry = ConfigOrphanEntry(
            path="~/.config/vlc",
            path_type="directory",
            orphan_reason="no_package_match",
            confidence=0.70,
        )

        assert entry.size_bytes is None
        assert entry.mtime is None

    def test_config_orphan_entry_frozen(self) -> None:
        """ConfigOrphanEntry is immutable."""
        from popctl.advisor.exchange import ConfigOrphanEntry
        from pydantic import ValidationError

        entry = ConfigOrphanEntry(
            path="~/.config/vlc",
            path_type="directory",
            orphan_reason="no_package_match",
            confidence=0.70,
        )

        with pytest.raises(ValidationError):
            entry.path = "changed"  # type: ignore[misc]

    def test_config_orphan_entry_serialization(self) -> None:
        """ConfigOrphanEntry serializes correctly via model_dump."""
        from popctl.advisor.exchange import ConfigOrphanEntry

        entry = ConfigOrphanEntry(
            path="~/.config/vlc",
            path_type="directory",
            size_bytes=4096,
            mtime="2024-01-15T10:00:00Z",
            orphan_reason="app_not_installed",
            confidence=0.70,
        )

        data = entry.model_dump()

        assert data["path"] == "~/.config/vlc"
        assert data["path_type"] == "directory"
        assert data["size_bytes"] == 4096
        assert data["mtime"] == "2024-01-15T10:00:00Z"
        assert data["orphan_reason"] == "app_not_installed"
        assert data["confidence"] == 0.70


# =============================================================================
# Test ScanExport with config_orphans
# =============================================================================


class TestScanExportConfigOrphans:
    """Tests for ScanExport config_orphans field."""

    def test_scan_export_config_orphans_defaults(self) -> None:
        """ScanExport defaults to empty config_orphans list."""
        export = ScanExport(
            scan_date="2026-01-25T12:00:00Z",
            system={"hostname": "test-host", "os": "Pop!_OS 24.04 LTS"},
            summary={"total_packages": 0},
            packages={"unknown": []},
        )

        assert export.config_orphans == []

    def test_scan_export_config_orphans_with_entries(self) -> None:
        """ScanExport accepts config orphan entries."""
        orphan = ConfigOrphanEntry(
            path="~/.config/vlc",
            path_type="directory",
            orphan_reason="no_package_match",
            confidence=0.70,
        )

        export = ScanExport(
            scan_date="2026-01-25T12:00:00Z",
            system={"hostname": "test-host", "os": "Pop!_OS 24.04 LTS"},
            summary={"total_packages": 0},
            packages={"unknown": []},
            config_orphans=[orphan],
        )

        assert len(export.config_orphans) == 1
        assert export.config_orphans[0].path == "~/.config/vlc"


# =============================================================================
# Test ScanExport with Config Orphans (integration)
# =============================================================================


class TestScanExportWithConfigs:
    """Tests for ScanExport with config_orphans field."""

    def test_scan_export_with_config_orphans(self) -> None:
        """ScanExport includes config_orphans when provided."""
        orphan = ConfigOrphanEntry(
            path="~/.config/vlc",
            path_type="directory",
            orphan_reason="app_not_installed",
            confidence=0.70,
        )

        export = ScanExport(
            scan_date="2026-01-25T12:00:00Z",
            system={"hostname": "test-host", "os": "Pop!_OS 24.04 LTS"},
            summary={"total_packages": 0},
            packages={"unknown": []},
            config_orphans=[orphan],
        )

        assert len(export.config_orphans) == 1
        assert export.config_orphans[0].path == "~/.config/vlc"

    def test_scan_export_without_config_orphans(self) -> None:
        """ScanExport defaults config_orphans to empty list."""
        export = ScanExport(
            scan_date="2026-01-25T12:00:00Z",
            system={"hostname": "test-host", "os": "Pop!_OS 24.04 LTS"},
            summary={"total_packages": 0},
            packages={"unknown": []},
        )

        assert export.config_orphans == []


# =============================================================================
# Test DecisionsResult with Configs
# =============================================================================


class TestDecisionsResultWithConfigs:
    """Tests for DecisionsResult with configs field."""

    def test_decisions_result_with_configs(self) -> None:
        """DecisionsResult includes config decisions when provided."""
        cfg_decisions = DomainDecisions(
            keep=[
                PathDecision(
                    path="~/.config/nvim",
                    reason="User-created Neovim configuration",
                    confidence=0.95,
                    category="editor",
                )
            ],
            remove=[
                PathDecision(
                    path="~/.config/vlc",
                    reason="VLC not installed",
                    confidence=0.85,
                    category="media",
                )
            ],
        )

        result = DecisionsResult(
            packages={
                "apt": SourceDecisions(),
                "flatpak": SourceDecisions(),
                "snap": SourceDecisions(),
            },
            configs=cfg_decisions,
        )

        assert result.configs is not None
        assert len(result.configs.keep) == 1
        assert len(result.configs.remove) == 1
        assert result.configs.keep[0].path == "~/.config/nvim"

    def test_decisions_result_without_configs(self) -> None:
        """DecisionsResult works without configs (backward compat)."""
        result = DecisionsResult(
            packages={
                "apt": SourceDecisions(),
                "flatpak": SourceDecisions(),
                "snap": SourceDecisions(),
            }
        )

        assert result.configs is None


# =============================================================================
# Test import_decisions with Configs
# =============================================================================


class TestImportDecisionsWithConfigs:
    """Tests for import_decisions with configs section."""

    def test_import_decisions_with_configs(self, tmp_path: Path) -> None:
        """import_decisions parses decisions.toml with [configs] section."""
        decisions_toml = """
[packages.apt]
keep = []
remove = []
ask = []

[packages.flatpak]
keep = []
remove = []
ask = []

[packages.snap]
keep = []
remove = []
ask = []

[configs]
keep = [
    { path = "~/.config/nvim", reason = "Neovim config", confidence = 0.95, category = "editor" },
]
remove = [
    { path = "~/.config/vlc", reason = "VLC removed", confidence = 0.85, category = "media" },
]
ask = [
    { path = "~/.config/foo", reason = "Unclear", confidence = 0.50, category = "unknown" },
]
"""
        decisions_path = tmp_path / "decisions.toml"
        decisions_path.write_text(decisions_toml)

        result = import_decisions(tmp_path)

        assert result.configs is not None
        assert len(result.configs.keep) == 1
        assert len(result.configs.remove) == 1
        assert len(result.configs.ask) == 1

        assert result.configs.keep[0].path == "~/.config/nvim"
        assert result.configs.keep[0].confidence == 0.95
        assert result.configs.keep[0].category == "editor"

        assert result.configs.remove[0].path == "~/.config/vlc"
        assert result.configs.remove[0].reason == "VLC removed"

        assert result.configs.ask[0].path == "~/.config/foo"
        assert result.configs.ask[0].confidence == 0.50

    def test_import_decisions_without_configs_backward_compat(self, tmp_path: Path) -> None:
        """import_decisions backward compat: no [configs] yields None."""
        decisions_toml = """
[packages.apt]
keep = []
remove = []
ask = []

[packages.flatpak]
keep = []
remove = []
ask = []

[packages.snap]
keep = []
remove = []
ask = []
"""
        decisions_path = tmp_path / "decisions.toml"
        decisions_path.write_text(decisions_toml)

        result = import_decisions(tmp_path)

        assert result.configs is None

    def test_import_decisions_configs_empty_lists(self, tmp_path: Path) -> None:
        """import_decisions handles empty config lists."""
        decisions_toml = """
[packages.apt]
keep = []
remove = []
ask = []

[packages.flatpak]
keep = []
remove = []
ask = []

[packages.snap]
keep = []
remove = []
ask = []

[configs]
keep = []
remove = []
ask = []
"""
        decisions_path = tmp_path / "decisions.toml"
        decisions_path.write_text(decisions_toml)

        result = import_decisions(tmp_path)

        assert result.configs is not None
        assert result.configs.keep == []
        assert result.configs.remove == []
        assert result.configs.ask == []

    def test_config_decisions_parsing(self, tmp_path: Path) -> None:
        """ConfigDecisions parsed correctly from TOML with all field types."""
        decisions_toml = """
[packages.apt]
keep = []
remove = []
ask = []

[packages.flatpak]
keep = []
remove = []
ask = []

[packages.snap]
keep = []
remove = []
ask = []

[configs]
keep = [
    { path = "~/.config/nvim", reason = "User config", confidence = 0.95, category = "editor" },
    { path = "~/.config/docker", reason = "Docker config", confidence = 0.99, category = "system" },
]
remove = [
    { path = "~/.config/vlc", reason = "VLC not installed", confidence = 0.85 },
]
ask = []
"""
        decisions_path = tmp_path / "decisions.toml"
        decisions_path.write_text(decisions_toml)

        result = import_decisions(tmp_path)

        assert result.configs is not None
        assert len(result.configs.keep) == 2
        assert result.configs.keep[0].category == "editor"
        assert result.configs.keep[1].category == "system"
        assert len(result.configs.remove) == 1
        # category is optional; TOML entry without category yields None
        assert result.configs.remove[0].category is None
